# Generated by Django 3.0.5 on 2021-07-27 18:57

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_addstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='expirydate',
            field=models.DateField(default=home.models.expiry),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='issuedate',
            field=models.DateField(auto_now=True),
        ),
    ]
